image: eclipse-temurin:21

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - export GIT_SHA=$CI_COMMIT_SHORT_SHA

# Snapshot release only releases on the maven under
# https://maven.idiotss.com/snapshots
# Auto trigger on push. Caches the build and gradle paths
snapshot:
  stage: deploy
  script: ./gradlew build publish
  tags:
    - linux
    - self-hosted
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
      - .gradle/
      - common/build
      - neoforge/build
    policy: pull-push

# Proper release. Publishes to CF and Modrinth and the maven under
# https://maven.idiotss.com/releases
# Requires manual trigger and can only run on protected branches
release:
  stage: deploy
  script: export RELEASE=true && ./gradlew build publish publishMods
  tags:
    - linux
    - self-hosted
  rules:
#   Only able to be triggered on protected branches
#   At the time of writing this the protected branches are 1.20.1 & 1.21.1
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      when: manual
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - build
      - .gradle/
      - common/build
      - neoforge/build
    policy: pull-push
