@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mrh0.createaddition.datagen.RecipeBuilders;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;