dependencies {
    compileOnly(project(":common"))
    neoForge("net.neoforged:neoforge:${project.neoforgeVersion}")

    modImplementation("com.simibubi.create:create-${rootProject.minecraftVersion}:${rootProject.createVersion}:slim") { transitive = false }
    modImplementation("net.createmod.ponder:Ponder-NeoForge-${minecraftVersion}:${ponderVersion}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraftVersion}:${flywheelVersion}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraftVersion}:${flywheelVersion}")
    modApi("com.tterrag.registrate:Registrate:${rootProject.registrateVersion}")

    modRuntimeOnly("maven.modrinth:createaddition:neoforge-1.21.1-1.5.8")
    modRuntimeOnly("org.appliedenergistics:appliedenergistics2:${appliedEnergisticsVersion}")

    compileOnly("io.github.llamalad7:mixinextras-common:0.5.0")
    annotationProcessor(implementation(include("io.github.llamalad7:mixinextras-neoforge:0.5.0")))
}

processResources {
    from(project(":common").sourceSets.main.resources)
    inputs.property "version", rootProject.version.replaceAll("\\+.*-mc", "\\+mc")
    inputs.property "minecraftVersion", rootProject.minecraftVersion
    inputs.property "neoforgeVersionRange", project.neoforgeVersionRange
    inputs.property "eslVersion", rootProject.eslVersion
    inputs.property "createVersion", rootProject.createVersionShort

    filesMatching("META-INF/neoforge.mods.toml") {
        expand "version": rootProject.version.replaceAll("\\+.*-mc", "\\+mc"),
        "minecraftVersion": rootProject.minecraftVersion,
        "neoforgeVersionRange": project.neoforgeVersionRange,
        "eslVersion": rootProject.eslVersion,
        "createVersion": rootProject.createVersionShort
    }
}

compileJava {
    source(project(":common").sourceSets.main.allSource)
}

var modId = rootProject.modId


loom {
    runs {
        datagen {
            data()
            programArgs("--all", "--mod", "${modId}")
            programArgs("--output", file("src/generated/resources").absolutePath)
            programArgs("--existing", file("../common/src/main/resources").absolutePath)
        }
    }
}

// https://modmuss50.github.io/mod-publish-plugin/
publishMods {
    file = jar.archiveFile
    changelog = rootProject.silk.changelog
    type = STABLE
    version = "$modVersion+mc$minecraftVersion"
    displayName = "$modVersion for Neoforge $minecraftVersion"
    modLoaders.add("neoforge")

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        projectId = "905861"
        clientRequired = true
        serverRequired = true
        requires("create")
        minecraftVersions.add(minecraftVersion)
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "FTeXqI9v"
        requires { // Requires Create
            id = "LNytGWDc"
        }
        minecraftVersions.add(minecraftVersion)
    }
}