@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package plus.dragons.createdragonsplus.common.fluids.tank;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;