modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="azimuth"
type="required"
versionRange="[1.4.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="struts"
type="required"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="createcasing"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dndecor"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create_connected"
type="optional"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tfmg"
type="incompatible"
reason="This mod is incompatible with TMFG that isnt 1.2.2c or version >1.2.2, you can download download 1.2.2c JAR from Bits 'n' Bobs page"
ordering="AFTER"
versionRange="(,1.2.2]"
side="BOTH"
