modLoader="javafml"
loaderVersion="${forgeVersionRange}"

license="BSD-3-Clause"
issueTrackerURL="https://gitlab.com/antarcticgardens/create-new-age"
showAsResourcePack=false

[[mods]]
modId="create_new_age"
version="${version}"
displayName="Create: New Age"
logoFile="icon.png"
authors="Antarctic Gardens"
description="An addon for the Create mod that adds integration with electricity"
displayTest="MATCH_VERSION"
displayURL="https://antarcticgardens.org/"

[[dependencies.create_new_age]]
    modId="forge"
    mandatory=true
    versionRange="${forgeVersionRange}"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_new_age]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraftVersion}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_new_age]]
    modId="esl"
    mandatory=true
    versionRange="[${eslVersion}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_new_age]]
    modId="create"
    mandatory=true
    versionRange="[${createVersion},6.1.0)"
    ordering="NONE"
    side="BOTH"
