@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mrh0.createaddition.recipe.charging;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;