@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mrh0.createaddition.blocks.tesla_coil;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;